### ISSUE TITLE
在 Databinding 项目中 NoClassDefFoundError

### ISSUE THREAD

**Issue by daimuruoji** [molihuan/mlhfileselectorlib#33]
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/chad/library/DataBinderMapperImpl;
                      E  	at com.liyan.viplibs.DataBinderMapperImpl.collectDependencies(DataBinderMapperImpl.java:69)
                      E  	at androidx.databinding.MergedDataBinderMapper.addMapper(MergedDataBinderMapper.java:63)
                      E  	at androidx.databinding.MergedDataBinderMapper.addMapper(MergedDataBinderMapper.java:65)
                      E  	at androidx.databinding.DataBinderMapperImpl.<init>(DataBinderMapperImpl.java:5)
                      E  	at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
                      E  	at androidx.databinding.DataBindingUtil.getDefaultComponent(DataBindingUtil.java:65)
                      E  	at com.xianggu.qnscan.databinding.ActivityMain2Binding.inflate(ActivityMain2Binding.java:60)

**Comment by daimuruoji** [comment]
Lcom/chad/library/是BaseRecyclerViewAdapterHelper
是 因为brvh 没有开启databinding
